import { NextRequest, NextResponse } from "next/server";
import connectToDatabase from "@/lib/mongodb";

export async function GET(req: NextRequest) {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    return NextResponse.json(
      { error: "MONGODB_URI not configured" },
      { status: 500 },
    );
  }
  const client = await connectToDatabase();
  const { searchParams } = new URL(req.url);
  const email = searchParams.get("email");
  if (!email) {
    return NextResponse.json({ error: "Missing email" }, { status: 400 });
  }

  try {
    const db = client.db();
    const user = await db.collection("users").findOne({ email });
    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }
    const roadmaps = await db
      .collection("roadmaps")
      .find({ userId: user._id })
      .toArray();
    // Fetch project ideas generated by the user
    const projectIdeas = await db
      .collection("projectIdeas")
      .find({ userId: user._id })
      .toArray();

    const userProfile = {
      name: user.name,
      email: user.email,
      avatarUrl: user.avatarUrl || "https://placehold.co/100x100.png",
      roadmaps,
      skills: user.skills || [],
      rank: user.rank || "Learner",
      activity: user.activity || [],
      projects: user.projects || [],
      achievements: user.achievements || [],
      projectIdeas: projectIdeas || [],
    };
    return NextResponse.json({ userProfile });
  } catch (err: any) {
    console.error("/api/user/profile error:", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
